// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProjectWeek29;

#nullable disable

namespace MiniProjectWeek29.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260717143605_Initial Creation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniProjectWeek29.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("PriceDollar")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MiniProjectWeek29.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            CurrencyCode = "USD",
                            Name = "Austin"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Sweden",
                            CurrencyCode = "SEK",
                            Name = "Sundsvall"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            CurrencyCode = "EUR",
                            Name = "Görlitz"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            CurrencyCode = "USD",
                            Name = "Raleigh"
                        },
                        new
                        {
                            Id = 5,
                            Country = "UAE",
                            CurrencyCode = "AED",
                            Name = "Sharjah"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Japan",
                            CurrencyCode = "JPY",
                            Name = "Sendai"
                        });
                });

            modelBuilder.Entity("MiniProjectWeek29.Computer", b =>
                {
                    b.HasBaseType("MiniProjectWeek29.Asset");

                    b.HasDiscriminator().HasValue("Computer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Lenovo",
                            Model = "ThinkPad T14 Gen 5",
                            OfficeId = 1,
                            PriceDollar = 1399,
                            PurchaseDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C001"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Model = "MacBook Air M3 13-inch",
                            OfficeId = 2,
                            PriceDollar = 1099,
                            PurchaseDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C002"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            Model = "EliteBook 840 G11",
                            OfficeId = 3,
                            PriceDollar = 1499,
                            PurchaseDate = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C003"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Dell",
                            Model = "Latitude 5450",
                            OfficeId = 4,
                            PriceDollar = 1249,
                            PurchaseDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C004"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Microsoft",
                            Model = "Surface Laptop 7",
                            OfficeId = 5,
                            PriceDollar = 1299,
                            PurchaseDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C005"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "ASUS",
                            Model = "Zenbook 14 OLED",
                            OfficeId = 6,
                            PriceDollar = 1199,
                            PurchaseDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C006"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Acer",
                            Model = "TravelMate P4",
                            OfficeId = 1,
                            PriceDollar = 999,
                            PurchaseDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C007"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Lenovo",
                            Model = "ThinkPad X1 Carbon Gen 12",
                            OfficeId = 2,
                            PriceDollar = 1799,
                            PurchaseDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C008"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Apple",
                            Model = "MacBook Pro M4 14-inch",
                            OfficeId = 3,
                            PriceDollar = 1599,
                            PurchaseDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C009"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "HP",
                            Model = "ProBook 450 G10",
                            OfficeId = 4,
                            PriceDollar = 949,
                            PurchaseDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C010"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Dell",
                            Model = "XPS 13 9340",
                            OfficeId = 5,
                            PriceDollar = 1399,
                            PurchaseDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C011"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "ASUS",
                            Model = "ExpertBook B5",
                            OfficeId = 6,
                            PriceDollar = 1099,
                            PurchaseDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C012"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Microsoft",
                            Model = "Surface Pro 11",
                            OfficeId = 1,
                            PriceDollar = 1199,
                            PurchaseDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C013"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Acer",
                            Model = "Swift Go 14",
                            OfficeId = 2,
                            PriceDollar = 899,
                            PurchaseDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C014"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Lenovo",
                            Model = "ThinkCentre M90q Gen 5",
                            OfficeId = 3,
                            PriceDollar = 1049,
                            PurchaseDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C015"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Apple",
                            Model = "Mac mini M4",
                            OfficeId = 4,
                            PriceDollar = 599,
                            PurchaseDate = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C016"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "HP",
                            Model = "ZBook Firefly 14 G11",
                            OfficeId = 5,
                            PriceDollar = 1699,
                            PurchaseDate = new DateTime(2024, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C017"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Dell",
                            Model = "Precision 3590",
                            OfficeId = 6,
                            PriceDollar = 1549,
                            PurchaseDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C018"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "ASUS",
                            Model = "ROG Zephyrus G14",
                            OfficeId = 1,
                            PriceDollar = 1599,
                            PurchaseDate = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C019"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Lenovo",
                            Model = "ThinkPad E14 Gen 5",
                            OfficeId = 2,
                            PriceDollar = 849,
                            PurchaseDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C020"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Dell",
                            Model = "OptiPlex 7010",
                            OfficeId = 3,
                            PriceDollar = 899,
                            PurchaseDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C021"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "HP",
                            Model = "EliteDesk 800 G6",
                            OfficeId = 4,
                            PriceDollar = 1099,
                            PurchaseDate = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C022"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Apple",
                            Model = "MacBook Pro M1 13-inch",
                            OfficeId = 5,
                            PriceDollar = 1299,
                            PurchaseDate = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C023"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Acer",
                            Model = "Aspire 5",
                            OfficeId = 6,
                            PriceDollar = 699,
                            PurchaseDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C024"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Microsoft",
                            Model = "Surface Laptop Studio 2",
                            OfficeId = 1,
                            PriceDollar = 1999,
                            PurchaseDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "C025"
                        });
                });

            modelBuilder.Entity("MiniProjectWeek29.Smartphone", b =>
                {
                    b.HasBaseType("MiniProjectWeek29.Asset");

                    b.HasDiscriminator().HasValue("Smartphone");

                    b.HasData(
                        new
                        {
                            Id = 26,
                            Brand = "Apple",
                            Model = "iPhone 16",
                            OfficeId = 1,
                            PriceDollar = 799,
                            PurchaseDate = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S001"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Samsung",
                            Model = "Galaxy S25",
                            OfficeId = 2,
                            PriceDollar = 799,
                            PurchaseDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S002"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Google",
                            Model = "Pixel 8",
                            OfficeId = 3,
                            PriceDollar = 699,
                            PurchaseDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S003"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "OnePlus",
                            Model = "OnePlus 13",
                            OfficeId = 4,
                            PriceDollar = 899,
                            PurchaseDate = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S004"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Sony",
                            Model = "Xperia 1 VI",
                            OfficeId = 5,
                            PriceDollar = 1299,
                            PurchaseDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S005"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Samsung",
                            Model = "Galaxy A55",
                            OfficeId = 6,
                            PriceDollar = 449,
                            PurchaseDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S006"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Apple",
                            Model = "iPhone 15",
                            OfficeId = 1,
                            PriceDollar = 699,
                            PurchaseDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S007"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Google",
                            Model = "Pixel 8a",
                            OfficeId = 2,
                            PriceDollar = 499,
                            PurchaseDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S008"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Motorola",
                            Model = "Edge 50 Pro",
                            OfficeId = 3,
                            PriceDollar = 649,
                            PurchaseDate = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S009"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Samsung",
                            Model = "Galaxy Z Flip6",
                            OfficeId = 4,
                            PriceDollar = 1099,
                            PurchaseDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S010"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Apple",
                            Model = "iPhone 16 Pro",
                            OfficeId = 5,
                            PriceDollar = 999,
                            PurchaseDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S011"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "OnePlus",
                            Model = "OnePlus 12",
                            OfficeId = 6,
                            PriceDollar = 799,
                            PurchaseDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S012"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Sony",
                            Model = "Xperia 5 V",
                            OfficeId = 1,
                            PriceDollar = 999,
                            PurchaseDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S013"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Google",
                            Model = "Pixel 7 Pro",
                            OfficeId = 2,
                            PriceDollar = 899,
                            PurchaseDate = new DateTime(2022, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S014"
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Samsung",
                            Model = "Galaxy S23",
                            OfficeId = 3,
                            PriceDollar = 799,
                            PurchaseDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S015"
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Motorola",
                            Model = "Moto G85",
                            OfficeId = 4,
                            PriceDollar = 399,
                            PurchaseDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S016"
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Apple",
                            Model = "iPhone 14",
                            OfficeId = 5,
                            PriceDollar = 699,
                            PurchaseDate = new DateTime(2021, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "S017"
                        });
                });

            modelBuilder.Entity("MiniProjectWeek29.Asset", b =>
                {
                    b.HasOne("MiniProjectWeek29.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });
#pragma warning restore 612, 618
        }
    }
}
